### ISSUE TITLE
line numbers on the asm block 

### ISSUE THREAD

**Issue by 8thMage** [Microsoft/microsoft-pdb#16]
you write this struct: 

struct CV_Line_t {
        unsigned long   offset;             // Offset to start of code bytes for line number
        unsigned long   linenumStart:24;    // line where statement/expression starts
        unsigned long   deltaLineEnd:7;     // delta to line where statement ends (optional)
        unsigned long   fStatement:1;       // true if a statement linenumber, else an expression line num
};

but i find the value 0x80f00f00 for the second unsigned long, which means that the line number is 0xf00f00 which is not a valid line number. can it be that you added more bits to the delta? can you help me with that?
thanks, the mage.

**Comment by VCZYK** [comment]
0xf00f00 is a special line number that our compiler generates to hint the debugger that in source view debugging the debugger should do something special on code having this line number.  Another strange line number we might see is 0xfeefee.
