### ISSUE TITLE
Maybe cvconst.h should also be included?

### ISSUE THREAD

**Issue by lygstate** [Microsoft/microsoft-pdb#3]
On the other hand, maybe these two header files should be re-licensed so that other opensource project can include it directly but not rewrite it.

**Comment by AndrewPardoe** [comment]
Assigning to Jim to investigate publishing cvconst.h.

@lygstate, what kind of license are you suggesting? cvinfo.h is published as MIT license. That gives you the right to do pretty much whatever you want, provided that you preserve attribution.

**Comment by JimRadigan** [comment]
Hi,
I'm working to get a lot more code out there and provide a dumper that can crack a binary file to dump the code view records. 
-Jim

**Comment by zjturner** [comment]
`cvconst.h` is already published as part of the DIA SDK.  Although admittedly it's somewhat difficult to figure out what the license terms of that file are.

**Comment by pombredanne** [comment]
@AndrewPardoe IMHO keeping up with the MIT would make sense

**Comment by lygstate** [comment]
@AndrewPardoe Yes, MIT is OK.

**Comment by JimRadigan** [comment]
Hi - Just checked in the cvconst.h that was requested and continuing towards a cvdump.exe with all the source code for its implementation.  cvdump.exe will crack a binary and dump the debug information which is in the code view format.

**Comment by pombredanne** [comment]
@JimRadigan this https://github.com/Microsoft/microsoft-pdb/commit/f26e0df8d4cc6d18066702355f2fd68838d31bfd is awesome! Thanks!

**Comment by AndrewPardoe** [comment]
Thanks, Jim, for getting this added to the repo.
