### ISSUE TITLE
Please provide a way to convert older style pdb files into the current format.

### ISSUE THREAD

**Issue by mdell-seradex** [Microsoft/microsoft-pdb#40]
I have several older style pdb files built with different compilers (VB6 for instance) but these can no longer be used for debugging purposes with Visual Studio 2017+.
Please provide a conversion/upgrade tool to recreate the pdb file in a compatible format.

Thank you

**Comment by zjturner** [comment]
This is certainly an interesting use case.  I think it's unlikely that Microsoft will ever decide to support this given the number of customers which are probably impacted, but LLVM has produced a fully working, completely open source implementation of PDB reading and writing.  I think your most likely path to making this possible is to implement the functionality yourself in LLVM (either upstream or in a fork).

**Comment by paddymcd-MSFT** [comment]
Please open a ticket for this feature request on https://developercommunity.visualstudio.com/ 

This repo was for information only and is not part of the live codebase for the PDB engine shipped with Visual Studio.

**Comment by mdell-seradex** [comment]
Done.
https://developercommunity.visualstudio.com/idea/509038/please-provide-a-way-to-convert-older-style-pdb-fi.html
