### ISSUE TITLE
Information about the PE format?

### ISSUE THREAD

**Issue by larsbrinkhoff** [Microsoft/microsoft-pdb#5]
How about detailed information about the PE format?

I have software to generate a PE executable image that works fine in Windows XP/Vista/7, but not in Window 8/10.  I had to guess what to change to make the executable work.

**Comment by avakar** [comment]
Are you missing something here: https://msdn.microsoft.com/en-us/windows/hardware/gg463119.aspx?

**Comment by larsbrinkhoff** [comment]
Yes, what's missing are the exact requirements for an executable image.  Which parts of the optional header are really optional?  Which ranges are acceptable for individual fields?

For example, my executable PE originally didn't include any data directories.  The specification describes them as optional, but Windows 8 didn't like that.

**Comment by williballenthin** [comment]
[This](https://code.google.com/p/corkami/wiki/PE) wiki describes in detail the fields and their interpretations that the loader uses.

**Comment by larsbrinkhoff** [comment]
Thanks, I've been in touch with @angea.

However, my idea is that there ought to be official information from Microsoft.

**Comment by pombredanne** [comment]
:+1:

**Comment by AndrewPardoe** [comment]
Thanks. I can't promise any official documentation but I've added these links to an External Resources document in the repo.
