### ISSUE TITLE
objcrt.pdb not loaded

### ISSUE THREAD

**Issue by swa6589** [Microsoft/microsoft-pdb#7]
We are trying to convert our IOS project to Windows using vsimporter.
Very often we are getting the error message objcrt.pdb and Foundation.pdb not loaded.
We are not able to understand the exact issue. If anyone can explain it that would be helpful.

Thanks & Regards,
Swathi

**Comment by AndrewPardoe** [comment]
Hi Swathi,

You should raise an issue on this repo: https://github.com/Microsoft/WinObjC. They're the owners for vsimporter. We're in close contact with that team and will help them if there is in fact a PDB issue.

Andrew
